ci: deploy echo-app on local environment

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -103,8 +103,8 @@ jobs:
           name: db-dump
           path: rollupsdb-*
   
-  local_test:
-    name: Integration tests (Espresso Local)
+  local_e2e_test:
+    name: e2e tests (Espresso Local)
     runs-on: ubuntu-latest
     needs: [build]
 
@@ -184,18 +184,52 @@ jobs:
             --rm --network=host \
             --name c_espresso espresso
 
-      - name: Run integration tests
+      # - name: Run integration tests
+      #   env:
+      #     CARTESI_CONTRACTS_INPUT_BOX_ADDRESS: '0x593E5BCf894D6829Dd26D0810DA7F064406aebB6'
+      #     CARTESI_CONTRACTS_INPUT_BOX_DEPLOYMENT_BLOCK_NUMBER: '10'
+      #     CARTESI_POSTGRES_ENDPOINT: 'postgres://postgres:password@localhost:5433/rollupsdb?sslmode=disable'
+      #     ESPRESSO_BASE_URL: 'http://localhost:24000'
+      #     ESPRESSO_STARTING_BLOCK: '1490657'
+      #     ESPRESSO_NAMESPACE: '55555'
+      #     ESPRESSO_SERVICE_ENDPOINT: '0.0.0.0:8080'
+      #   run: |
+      #     export $(cat ./ci/env.nodev2-espressolocal | grep -v '^#') 
+      #     go test --timeout 1m -p 1 ./...
+
+      - name: Deploy Echo Dapp
         env:
-          CARTESI_CONTRACTS_INPUT_BOX_ADDRESS: '0x593E5BCf894D6829Dd26D0810DA7F064406aebB6'
-          CARTESI_CONTRACTS_INPUT_BOX_DEPLOYMENT_BLOCK_NUMBER: '10'
-          CARTESI_POSTGRES_ENDPOINT: 'postgres://postgres:password@localhost:5433/rollupsdb?sslmode=disable'
-          ESPRESSO_BASE_URL: 'http://localhost:24000'
-          ESPRESSO_STARTING_BLOCK: '1490657'
-          ESPRESSO_NAMESPACE: '55555'
-          ESPRESSO_SERVICE_ENDPOINT: '0.0.0.0:8080'
+          ACCOUNT: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
+          PRIVATE_KEY: 'ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'
+          RPC_URL: 'http://localhost:8545'
         run: |
-          export $(cat ./ci/env.nodev2-espressolocal | grep -v '^#') 
-          go test --timeout 1m -p 1 ./...
+          docker exec c_espresso cartesi-rollups-cli app deploy -v -n echo-dapp -o $ACCOUNT -O $ACCOUNT -k $PRIVATE_KEY -r $RPC_URL -t applications/echo-dapp/
+
+      - name: Send input transaction
+        env:
+          SENDER_PRIVATE_KEY: ${{ secrets.SENDER_PRIVATE_KEY }}
+        run: |
+          git clone --recurse-submodules https://github.com/Calindra/nonodo.git
+          cd nonodo/eip712-client-js
+          npm i
+          APP_ADDRESS=0x5a205Fcb6947e200615B75C409ac0aa486D77649 node index.js
+
+      - name: Query Database for Output
+        run: |
+          MAX_RETRIES=30
+          for i in $(seq 1 $MAX_RETRIES); do
+            RESULT=$(docker exec -i postgres psql -U postgres -d rollupsdb -t -c "SELECT * FROM public.output;")
+            if [[ "$RESULT" =~ "deadbeef" ]]; then
+              echo "Result found: $RESULT"
+              exit 0
+            fi
+            echo "Result: $RESULT"
+            echo "Waiting for result... attempt $i"
+            sleep 5
+          done
+          echo "Timeout reached: result not found"
+          docker logs --timestamps c_espresso
+          exit 1
 
   integration_test:
     name: Integration tests (Decaf)
